include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'


# Julia versions

julia:1.0:
  extends:
    - .julia:1.0
    - .test

julia:1.1:
  extends:
    - .julia:1.1
    - .test

julia:1.2:
  extends:
    - .julia:1.2
    - .test

julia:1.3:
  extends:
    - .julia:1.3
    - .test

julia:nightly:
  extends:
    - .julia:nightly
    - .test
  allow_failure: true


# reverse tests

# NOTE: reverse testing is tricky because of Manifests. we instantiate both, give priority
#       to this package's Manifest, and manually run tests outside of the test environment.
#       that means we have to manually install CuArrays' test dependencies though.

cuarrays:
  extends: .julia:1.2
  tags:
    - nvidia
    - sm_75
  image: juliagpu/cuda:10.1-cudnn7-cutensor-devel-ubuntu18.04
  script:
    - export CUARRAYS="$HOME/.julia/dev/CuArrays"
    - julia -e 'using Pkg;
                Pkg.develop("CuArrays");'
    - julia --project -e 'using Pkg;
                          Pkg.instantiate()'
    - julia --project=$CUARRAYS -e 'using Pkg;
                                    Pkg.instantiate();
                                    Pkg.add(["FFTW", "ForwardDiff"])'
    - JULIA_LOAD_PATH=".:$CUARRAYS::" julia $CUARRAYS/test/runtests.jl
  allow_failure: true


# other tasks

coverage:
  extends:
    - .julia:1.2
    - .coverage
